### PR TITLE
Fix - onReportSubmitHandler freeze on iOS

### LINKED ISSUE #475: shake causes iOS getting freeze when onReportSubmitHandler called
### Steps to Reproduce the Problem

1) Handle onReportSubmitHandler with a callback
```javascript
InstabugRn.onReportSubmitHandler((report: Report) => {
      if (this.reportTags && this.reportTags.length) {
        // add tags for individual report
        for (const tag of this.reportTags) {
          report.appendTag(tag);
        }
        // reset the report tags
        this.reportTags = [];
      }
    });
```

2) Enable shake to call out the bug report
```javascript
InstabugRn.startWithToken(this.appToken, [InstabugRn.invocationEvent.shake]);
```

3) Run the App
4) Shake the phone

I found eventually it's about the invisible function in the Instabug's iOS SDK `setWillSendReportHandler_private` call causing the freeze, if I just replace it with 
```objective-c
Instabug.willSendReportHandler = ^IBGReport * _Nonnull(IBGReport * _Nonnull report) {
            NSArray *tagsArray = report.tags;
             NSArray *instabugLogs= report.instabugLogs;
             NSArray *consoleLogs= report.consoleLogs;
             NSDictionary *userAttributes= report.userAttributes;
             NSArray *fileAttachments= report.fileLocations;
             NSDictionary *dict = @{ @"tagsArray" : tagsArray, @"instabugLogs" : instabugLogs, @"consoleLogs" : consoleLogs,       @"userAttributes" : userAttributes, @"fileAttachments" : fileAttachments};
            [self sendEventWithName:@"IBGpreSendingHandler" body:dict];

            currentReport = report;
            return report;
        };
```
and 
```objective-c
RCT_EXPORT_METHOD(submitReport) {
    if (globalReportCompletionHandler && currentReport) {
        globalReportCompletionHandler(currentReport);
    }
    currentReport = nil;
}
```
Everything goes fine, but I am very concerned `globalReportCompletionHandler` will be always `nil` and don't know what bad things will happen even I can normally see the report in Instabug's dashboard.

### Expected Behavior

Present the bug report window as expectation

### Actual Behavior

App getting freeze, any tap on the screen without response.

### SDK Version

instabug-reactnative 9.0.7

### React Native, iOS and Android Versions

React Native 0.61.5
iOS 13.2

### Device Model

iPhone XS (Real device)
iPhone 11 (Simulator)

### PR DESCRIPTION
**Pull request by alyezz**
* Fixes #475

### CODE REVIEW

File: ios/RNInstabug/InstabugReactBridge.m [hunk 1]
```diff
@@ -115,21 +115,21 @@ - (dispatch_queue_t)methodQueue {
...
-            NSArray *instabugLogs= report.instabugLogs;
-            NSArray *consoleLogs= report.consoleLogs;
-            NSDictionary *userAttributes= report.userAttributes;
-            NSArray *fileAttachments= report.fileLocations;
-            NSDictionary *dict = @{ @"tagsArray" : tagsArray, @"instabugLogs" : instabugLogs, @"consoleLogs" : consoleLogs,       @"userAttributes" : userAttributes, @"fileAttachments" : fileAttachments};
+             NSArray *instabugLogs= report.instabugLogs;
+             NSArray *consoleLogs= report.consoleLogs;
+             NSDictionary *userAttributes= report.userAttributes;
+             NSArray *fileAttachments= report.fileLocations;
+             NSDictionary *dict = @{ @"tagsArray" : tagsArray, @"instabugLogs" : instabugLogs, @"consoleLogs" : consoleLogs,       @"userAttributes" : userAttributes, @"fileAttachments" : fileAttachments};
```
Comment (AliAbdelfattah) [inline ios/RNInstabug/InstabugReactBridge.m:127]: Please undo the indentation.

File: ios/RNInstabug/InstabugReactBridge.m [hunk 2]
```diff
@@ -198,7 +198,6 @@ - (dispatch_queue_t)methodQueue {
 }
 
 RCT_EXPORT_METHOD(submitReport) {
-    globalReportCompletionHandler(currentReport);
```
Comment (AliAbdelfattah) [inline ios/RNInstabug/InstabugReactBridge.m:201]: Pending [slack conversation](https://instabugteam.slack.com/archives/G011GDPJ6LU/p1594214144001800).

**Review by AliAbdelfattah — APPROVED** [review]
